### ISSUE TITLE
Collect equipable item data

### ISSUE THREAD

**Issue by Little0smit** [Little0smit/ChunkTracker#11]
Collect all equpiable item data from osrs into json format.
Possibly use  [these awesome files](https://www.osrsbox.com/projects/osrsbox-db/#item-equipment-information) created by OSRSBOX.
The info required is: to be stored as an object per item in json format like so:

"Item": {
  "Name": "Name",
  "Equipable": true,
  "Stats":{
    "Offensive":[0,0,0,0,0],
    "Deffensive":[0,0,0,0,0],
    "Other":[0,0,0,0,0]
}

**Comment by osrsbox** [comment]
Hey @Little0smit - I could generate this data for you, and can make it in the format required. I can try my best to also redo it when there are changes in the database. Will put together the data and do a pull request for it.

**Comment by Little0smit** [comment]
Yo man, that'd be awesome. If there's any extra fields you think could be valuable/useful welcome to add.

**Comment by osrsbox** [comment]
Hey @Little0smit, just checking the format I have put together:

```
{
    "name":"Hunter cape(t)",
    "equipable":true,
    "stats":{
        "offensive":[
            0,
            0,
            0,
            0,
            0
        ],
        "defensive":[
            9,
            9,
            9,
            9,
            9
        ],
        "other":[
            0,
            0,
            0,
            4
        ]
    }
}
```

You can see other properties available in the item database on the [OSRSBox website project page](https://www.osrsbox.com/projects/osrsbox-db/). Let me know if you want to add anything, or change the format.

**Comment by Little0smit** [comment]
Would be useful to have slot it goes in, either as a new variable or as a 5th integer in the other info array. And skill reqs would be good to have now I think about it.

As for format looks good to me, and always possible for us to change about variable names within the program but I'll check with the person working on JSON importing now.

**Comment by Hannah-GBS** [comment]
Whether its a Members item or not would probably be useful, if we wanted to give users the option of Members or F2P.

**Comment by apan145** [comment]
I've been adding parsing of the other JSON files to the project but haven't comitted them yet. I've changed the data structure to look like this:
```
{
    "name": "mithrilSword",
    "offensiveStats":[16,11,-2,0,0],
    "defensiveStats":[0,2,1,0,0],
    "otherStats":[17,0,0,0,4],
    "type": "Melee",
    "slot": "MainHand"
  }
```
The order of the stats is
Offensive: stab, slash, crush, magic, ranged
Defensive: stab, slash, crush, magic, ranged
Other: strength, ranged strength, magic strength, prayer, attack speed

**Comment by Little0smit** [comment]
Yea happy with that layout, then I would just add on requirements and members as you've got them stored currently in your data @osrsbox

**Comment by Little0smit** [comment]
Also, maybe add itemID then that way we can always look up more info from your api if we really need, and for icons in future if required.

**Comment by osrsbox** [comment]
Based on the feedback - I have added examples of an equipable item and non-equipable item below. The order of the arrays are currently set to the format @apan145 specified. FYI - I do not have `type` in my database. And `slot` is generically classified to `weapon` as I do not distinguish between one hand or two hand (but thinking I might add this to the database). Reason for the `slot` naming conventions - this is what the OSRS Wiki uses - I usually stick to their conventions.

More than open to changing any of this format to what the needs of your project are. And also open to feedback about what properties are available in my item database, and what could be useful to add in the future.

Equipable item:

```
{
    "id":9949,
    "name":"Hunter cape(t)",
    "equipable":true,
    "members":true,
    "stats":{
        "offensive":[0,0,0,0,0],
        "defensive":[9,9,9,9,9],
        "other":[0,0,0,4,null]
    },
    "slot":"cape",
    "skill_reqs":[
        {
            "skill":"hunter",
            "level":99
        }
    ]
}
```

Not-equipable item:

```
{
    "id":9999,
    "name":"Hunter potion(4)",
    "equipable":false,
    "members":true,
    "stats":null,
    "slot":null,
    "skill_reqs":null
}
```

**Comment by Little0smit** [comment]
@osrsbox just so you're away small change in file's locations done in commit 9b5e2bddbc0128f8798c5162c56b81e4aae034d7 will mention this issue in the commit now

**Comment by osrsbox** [comment]
Thanks @Little0smit - I have the code for the data conversion to the required format. I will try to get this finished tomorrow.

**Comment by Little0smit** [comment]
Awesome, no huge rush if you can't as still plenty dev work till this is needed over dummy data.

**Comment by osrsbox** [comment]
@Little0smit Sorry it took me so long to sort this issue out. I have just opened a PR #46 which has the equipable item data in JSON format. I have written a Python script to achieve this, and will link to it when I have push it to my repo. Open to any feedback on the data (structure, errors etc.).

EDIT: The script I used to generate the data is available from: [https://github.com/osrsbox/osrsbox-db/blob/master/osrsbox/items_api_examples/generate_chunktracker_data.py](https://github.com/osrsbox/osrsbox-db/blob/master/osrsbox/items_api_examples/generate_chunktracker_data.py). It can easily be modified to change the structure/content of the generated data.

**Comment by Hannah-GBS** [comment]
Now that's some good stuff right there
