### ISSUE TITLE
Add a way for the program to take input data

### ISSUE THREAD

**Issue by apan145** [Little0smit/ChunkTracker#32]
For the program to work, it needs to be given some data, like the players current skills and unlocked chunks. There needs to be a way for the program to get these. Perhaps by .txt or by a GUI?

**Comment by Little0smit** [comment]
Thinking for initial development it will work on command line entry/or read from a file. Once Barebones Release is finished, some form of GUI can be implemented.
GUI designs/comments welcome in #33

**Comment by Hannah-GBS** [comment]
Could you pull account stats from the OSRS site itself? I've seen skills spreadsheets that pull your stats from the Highscores page (https://services.runescape.com/m=hiscore_oldschool/hiscorepersonal.ws?user1=loldudester)

**Comment by Little0smit** [comment]
Yea certainly possible, although would probably be a later goal, once main basic program is released and working.

**Comment by Little0smit** [comment]
**Working on this now**
