### ISSUE TITLE
Do we need to return all skills in Player.skillsToNextChunk()?

### ISSUE THREAD

**Issue by Little0smit** [Little0smit/ChunkTracker#41]
In Player.skillsToNextChunk() method the EnumMap returned contains all skills (even ones lower/equal to current stats). Do we need it to do this for a reason or can we simply return the ones still needing to be trained?
@apan145

**Comment by apan145** [comment]
I think it'll be fine to return only the ones needed to be trained.

**Comment by Little0smit** [comment]
Closed by #44
